<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="André Victor Ribeiro Amaral" />


<title>Case Study 05</title>

<script src="site_libs/header-attrs-2.13/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Linear Models</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="case_study_01.html">Case Study 01</a>
</li>
<li>
  <a href="case_study_02.html">Case Study 02</a>
</li>
<li>
  <a href="case_study_03.html">Case Study 03</a>
</li>
<li>
  <a href="case_study_04.html">Case Study 04</a>
</li>
<li>
  <a href="case_study_05.html">Case Study 05</a>
</li>
<li>
  <a href="case_study_06.html">Case Study 06</a>
</li>
<li>
  <a href="case_study_07.html">Case Study 07</a>
</li>
<li>
  <a href="case_study_08.html">Case Study 08</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://avramaral.github.io/">
    <span class="fa fa-globe"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Case Study 05</h1>
<h4 class="author">André Victor Ribeiro Amaral</h4>

</div>


<div id="objectives" class="section level1 unnumbered">
<h1 class="unnumbered">Objectives</h1>
<p>In this case study, we will fit a multiple linear regression model. However, different than <a href="./case_study_04.html">before</a>, we will work with more variables. To do so, we will check for correlation among covariates, see how to perform variable selection, fit a model, check the assumptions, interpret it, and predict (and plot) new values based on this fitted model. When in higher dimension, visualization is difficult (and unnecessary for most cases).</p>
</div>
<div id="introduction" class="section level1" number="1">
<h1 number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>For this problem, we will analyse a data set with 6 variable (1 response variable + 6 covariates). Although their meaning may not be stated, we will see how important feature selection is when performing multiple regression analysis. You can download the <code>.csv</code> file <a href="./datasets/data.csv">here</a>. The data set contains the following variables:</p>
<ol style="list-style-type: decimal">
<li><code>var1</code> (quantitative)</li>
<li><code>var2</code> (quantitative)</li>
<li><code>var3</code> (quantitative)</li>
<li><code>var4</code> (quantitative)</li>
<li><code>var5</code> (quantitative)</li>
<li><code>var6</code> (quantitative)</li>
<li><code>response</code> (quantitative)</li>
</ol>
</div>
<div id="exploring-the-data-set" class="section level1" number="2">
<h1 number="2"><span class="header-section-number">2</span> Exploring the data set</h1>
<p>In order to explore the data set and perform initial analyses, we have to read it (with <code>R</code>) first. Provided that the <code>.csv</code> file is saved within the <code>datasets/</code> folder, one can read the file in the following way.</p>
<pre class="r"><code>col.names &lt;- c(&#39;var1&#39;, &#39;var2&#39;, &#39;var3&#39;, &#39;var4&#39;, &#39;var5&#39;, &#39;var6&#39;, &#39;response&#39;)
data &lt;- read.csv(file = &#39;datasets/data.csv&#39;, header = FALSE, sep = &#39;,&#39;, col.names = col.names)
head(data, 5)</code></pre>
<pre><code>##       var1      var2     var3        var4     var5     var6 response
## 1 68.10730  95.83754 49.66851 0.015061421 2.090953 64.83720 218.5916
## 2 78.18420  97.69040 54.51643 0.042649961 4.320810 74.54103 245.8415
## 3 54.24527 105.20130 49.59829 0.005194938 4.948731 78.74680 264.0839
## 4 54.56271  97.41171 47.21550 0.021132252 5.127075 74.95861 251.3954
## 5 56.75478  95.57443 44.05604 0.027485738 1.801114 63.39468 214.6450</code></pre>
<p>Now, let’s see a summary of our data.</p>
<pre class="r"><code>summary(data)</code></pre>
<pre><code>##       var1            var2             var3            var4          
##  Min.   :50.94   Min.   : 92.32   Min.   :44.06   Min.   :0.0001482  
##  1st Qu.:56.45   1st Qu.: 95.77   1st Qu.:47.24   1st Qu.:0.0045800  
##  Median :64.21   Median : 98.57   Median :49.63   Median :0.0131564  
##  Mean   :63.96   Mean   : 99.73   Mean   :49.29   Mean   :0.0163943  
##  3rd Qu.:68.94   3rd Qu.:103.94   3rd Qu.:51.37   3rd Qu.:0.0249283  
##  Max.   :79.30   Max.   :107.66   Max.   :54.52   Max.   :0.0426500  
##       var5            var6          response    
##  Min.   :1.801   Min.   :63.08   Min.   :210.5  
##  1st Qu.:2.486   1st Qu.:69.98   1st Qu.:232.2  
##  Median :5.038   Median :74.97   Median :250.9  
##  Mean   :4.709   Mean   :75.77   Mean   :252.8  
##  3rd Qu.:6.493   3rd Qu.:81.05   3rd Qu.:270.3  
##  Max.   :9.055   Max.   :90.00   Max.   :298.0</code></pre>
<p>There are no missing values so that we can jump in into the exploratory analyses. However, since we want to use most information from this data set, it is not easy to visualize how <code>strength</code> can be written as a function of more than two variables at the same time. But it might be useful to see how variables are correlated. To do this, we can use the <code>scatterplotMatrix()</code> function from the <code>car</code> package, and the <code>corrplot.mixed()</code> function from the <code>corrplot</code> package.</p>
<pre class="r"><code>library(&#39;car&#39;)

scatterplotMatrix(data)</code></pre>
<p><img src="case_study_05_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Specially when there are too many variables or too many data points per plot, it might be difficult to analyse all the details, but from the above plot we can have a rough idea on how each variable can be written as a function of others.</p>
<pre class="r"><code>library(&#39;corrplot&#39;)

corrplot.mixed(cor(data))</code></pre>
<p><img src="case_study_05_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>However, from the above plot we may have clearer information about the correlation between pair of variables. For instance, <code>var1</code> and <code>var3</code> are highly correlated, as well as <code>var5</code> and <code>var6</code>, <code>var5</code> and <code>response</code>, and <code>var6</code> and <code>response</code>. This information can help us having an idea on which attributes better explain the dependent variable.</p>
</div>
<div id="fitting-a-model" class="section level1" number="3">
<h1 number="3"><span class="header-section-number">3</span> Fitting a model</h1>
<p>Our very first task will be fitting a model with all variables so that we can try to explain how the response variable relates to the covariates. We can do this in the following way.</p>
<pre class="r"><code>model &lt;- lm(formula = response ~ ., data = data)
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = response ~ ., data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.29614 -0.41203 -0.05714  0.32644  1.68448 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.01567    4.31348  -0.004   0.9971    
## var1         0.16437    0.05915   2.779   0.0129 *  
## var2         1.65363    0.25551   6.472 5.74e-06 ***
## var3        -0.24772    0.15677  -1.580   0.1325    
## var4        15.25598   13.40879   1.138   0.2710    
## var5         7.85702    1.19346   6.583 4.65e-06 ***
## var6         0.69112    0.38603   1.790   0.0912 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8177 on 17 degrees of freedom
## Multiple R-squared:  0.9992, Adjusted R-squared:  0.9989 
## F-statistic:  3540 on 6 and 17 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>From the above summary table, we may see two covariates that might not be significant, namely <code>var3</code>, <code>var4</code>, and <code>var6</code>. As we prefer simpler models over more complex models, provided they have the same performance, let’s remove the one with the highest p-value first (<code>var4</code>). We can do this using the <code>update()</code> function.</p>
<pre class="r"><code>model2 &lt;- update(model, ~. - var4)
summary(model2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = response ~ var1 + var2 + var3 + var5 + var6, data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.56817 -0.37178 -0.02967  0.30375  1.88355 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.23242    4.34438  -0.053   0.9579    
## var1         0.15298    0.05877   2.603   0.0180 *  
## var2         1.57953    0.24908   6.341 5.64e-06 ***
## var3        -0.22602    0.15687  -1.441   0.1668    
## var5         7.46733    1.15258   6.479 4.29e-06 ***
## var6         0.81454    0.37349   2.181   0.0427 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8244 on 18 degrees of freedom
## Multiple R-squared:  0.9991, Adjusted R-squared:  0.9989 
## F-statistic:  4179 on 5 and 18 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Now, let’s remove <code>coarse_aggregate</code>.</p>
<pre class="r"><code>model3 &lt;- update(model2, ~. - var3)
summary(model3)</code></pre>
<pre><code>## 
## Call:
## lm(formula = response ~ var1 + var2 + var5 + var6, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.6041 -0.4214 -0.0859  0.4792  1.5974 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.78392    4.44833  -0.176   0.8620    
## var1         0.07899    0.02937   2.690   0.0145 *  
## var2         1.46614    0.24293   6.035 8.33e-06 ***
## var5         7.19347    1.16854   6.156 6.46e-06 ***
## var6         0.90352    0.37864   2.386   0.0276 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8474 on 19 degrees of freedom
## Multiple R-squared:  0.999,  Adjusted R-squared:  0.9988 
## F-statistic:  4944 on 4 and 19 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Although <code>var6</code> has a p-value of <code>0.0276</code> and we already know that it is highly correlated with <code>var5</code>, let’s keep it for now. However, in order to have sufficiently simpler models, we can also compute and analyse the Variance Inflation Factor (VIF), which is a <strong>measure of the amount of multicollinearity in a set of multiple regression variables</strong>. According to <a href="https://www.investopedia.com/terms/v/variance-inflation-factor.asp">this page</a> <em>the VIF for a regression model variable is equal to the ratio of the overall model variance to the variance of a model that includes only that single independent variable. This ratio is calculated for each independent variable. A high VIF indicates that the associated independent variable is highly collinear with the other variables in the model</em>. Also, as a rule of thumb, we can exclude variables with VIF greater than 2, provided we do this for one variable at a time. To do this, we can use the <code>vif()</code> function from the <code>car</code> package.</p>
<pre class="r"><code>vif(model3)</code></pre>
<pre><code>##       var1       var2       var5       var6 
##   1.740913  44.823922 211.048276 271.824355</code></pre>
<p>As we expected, <code>var6</code> can be excluded from our model.</p>
<pre class="r"><code>model4 &lt;- update(model3, ~. - var6)
vif(model4)</code></pre>
<pre><code>##     var1     var2     var5 
## 1.004377 1.012391 1.008489</code></pre>
<pre class="r"><code>summary(model4)</code></pre>
<pre><code>## 
## Call:
## lm(formula = response ~ var1 + var2 + var5, data = data)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.2887 -0.6780 -0.1195  0.3639  1.8939 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -5.49457    4.42946  -1.240    0.229    
## var1         0.12457    0.02479   5.026 6.48e-05 ***
## var2         2.03923    0.04057  50.268  &lt; 2e-16 ***
## var5         9.97519    0.08976 111.135  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.9416 on 20 degrees of freedom
## Multiple R-squared:  0.9988, Adjusted R-squared:  0.9986 
## F-statistic:  5337 on 3 and 20 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>Alternatively, we can do this model selection procedure according to another criteria, namely Akaike Information Criterion (AIC), which is used for evaluating how well a model fits the data it was generated from. AIC is used to compare different possible models and determine which one is the best fit for the data <a href="https://www.scribbr.com/statistics/akaike-information-criterion/">(reference)</a>. In <code>R</code>, we can use the <code>stepAIC()</code> function from the <code>MASS</code> package to automatize this procedure.</p>
<pre class="r"><code>library(&#39;MASS&#39;)

(modelAIC &lt;- stepAIC(model, direction = &#39;both&#39;))</code></pre>
<pre><code>## Start:  AIC=-3.93
## response ~ var1 + var2 + var3 + var4 + var5 + var6
## 
##        Df Sum of Sq    RSS     AIC
## - var4  1    0.8656 12.233 -4.1737
## &lt;none&gt;              11.368 -3.9349
## - var3  1    1.6697 13.037 -2.6458
## - var6  1    2.1433 13.511 -1.7894
## - var1  1    5.1645 16.532  3.0539
## - var2  1   28.0073 39.375 23.8818
## - var5  1   28.9812 40.349 24.4681
## 
## Step:  AIC=-4.17
## response ~ var1 + var2 + var3 + var5 + var6
## 
##        Df Sum of Sq    RSS     AIC
## &lt;none&gt;              12.233 -4.1737
## + var4  1    0.8656 11.368 -3.9349
## - var3  1    1.4109 13.644 -3.5540
## - var6  1    3.2324 15.466 -0.5465
## - var1  1    4.6053 16.839  1.4947
## - var2  1   27.3292 39.562 21.9958
## - var5  1   28.5272 40.760 22.7117</code></pre>
<pre><code>## 
## Call:
## lm(formula = response ~ var1 + var2 + var3 + var5 + var6, data = data)
## 
## Coefficients:
## (Intercept)         var1         var2         var3         var5         var6  
##     -0.2324       0.1530       1.5795      -0.2260       7.4673       0.8145</code></pre>
<pre class="r"><code>summary(modelAIC)</code></pre>
<pre><code>## 
## Call:
## lm(formula = response ~ var1 + var2 + var3 + var5 + var6, data = data)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -1.56817 -0.37178 -0.02967  0.30375  1.88355 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) -0.23242    4.34438  -0.053   0.9579    
## var1         0.15298    0.05877   2.603   0.0180 *  
## var2         1.57953    0.24908   6.341 5.64e-06 ***
## var3        -0.22602    0.15687  -1.441   0.1668    
## var5         7.46733    1.15258   6.479 4.29e-06 ***
## var6         0.81454    0.37349   2.181   0.0427 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 0.8244 on 18 degrees of freedom
## Multiple R-squared:  0.9991, Adjusted R-squared:  0.9989 
## F-statistic:  4179 on 5 and 18 DF,  p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>vif(modelAIC)</code></pre>
<pre><code>##       var1       var2       var3       var5       var6 
##   7.366028  49.794159   6.922008 216.948426 279.464063</code></pre>
<p>However, notice that <code>stepAIC()</code> only removed <code>var4</code>, and when we compute the VIF, we see that we can still have problems with multicollinearity (which might generate high variance of the estimated coefficients). Now, removing the variables with high VIF, we have</p>
<pre class="r"><code>modelAIC2 &lt;- update(modelAIC, ~. - var6)
vif(modelAIC2)</code></pre>
<pre><code>##     var1     var2     var3     var5 
## 5.832034 2.231948 6.732781 1.008490</code></pre>
<pre class="r"><code>modelAIC3 &lt;- update(modelAIC2, ~. - var3)
vif(modelAIC3)</code></pre>
<pre><code>##     var1     var2     var5 
## 1.004377 1.012391 1.008489</code></pre>
<p>Which is the same model as before. We will take this as our minimal model.</p>
<p>However, we still have to do a residual analysis. For doing this, we will do the “Residuals vs Fitted” and “Normal Q-Q” plots and run the appropriate tests, as before.</p>
<pre class="r"><code>plot(model4, which = c(1, 2))</code></pre>
<p><img src="case_study_05_files/figure-html/unnamed-chunk-12-1.png" width="672" /><img src="case_study_05_files/figure-html/unnamed-chunk-12-2.png" width="672" /></p>
<p>From the plots, the assumptions of equal variance and normality for the residuals seem to hold. However, as fewer data points make the visual analysis difficult, it is also important to run the tests, namely, <code>ncvTest()</code> and <code>shapiro.test()</code> for the residuals (<code>resid()</code>).</p>
<pre class="r"><code>ncvTest(model4)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 1.481062, Df = 1, p = 0.22361</code></pre>
<pre class="r"><code>shapiro.test(resid(model4))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resid(model4)
## W = 0.93153, p-value = 0.1055</code></pre>
<p>From the tests results, we fail to reject the null hypotheses—meaning that there is no evidence from the data that the assumptions of equal variance and normality for the residuals do not hold.</p>
<p>Our final model is</p>
<p><span class="math display">\[\begin{align*}
\texttt{response}_i &amp;= -5.495 + 0.125\texttt{var1}_i + 2.039\texttt{var2}_i + 9.975\texttt{var5}_i
\end{align*}\]</span></p>
</div>
<div id="predicting-unknown-values" class="section level1" number="4">
<h1 number="4"><span class="header-section-number">4</span> Predicting unknown values</h1>
<p>Now that we have a “good” fitted model, we can predict the value of <code>response</code> for new values of <code>var1</code>, <code>var2</code>, and <code>var5</code>. For instance, we can predict the value of <code>response</code>, such that <code>var1</code>, <code>var2</code> and <code>var5</code> are equal to 55, 100, and 70, respectively. We can also include a confidence and a prediction interval.</p>
<pre class="r"><code>newdata &lt;- data.frame(var1 = 55, var2 = 100, var5 = 70)

(pred1 &lt;- predict(object = model4, newdata = newdata, interval = &#39;confidence&#39;))</code></pre>
<pre><code>##        fit      lwr      upr
## 1 903.5433 891.3115 915.7751</code></pre>
<pre class="r"><code>(pred2 &lt;- predict(object = model4, newdata = newdata, interval = &#39;prediction&#39;))</code></pre>
<pre><code>##        fit      lwr      upr
## 1 903.5433 891.1548 915.9318</code></pre>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
