<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="André Victor Ribeiro Amaral" />


<title>Case Study 06</title>

<script src="site_libs/header-attrs-2.13/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Linear Models</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="case_study_01.html">Case Study 01</a>
</li>
<li>
  <a href="case_study_02.html">Case Study 02</a>
</li>
<li>
  <a href="case_study_03.html">Case Study 03</a>
</li>
<li>
  <a href="case_study_04.html">Case Study 04</a>
</li>
<li>
  <a href="case_study_05.html">Case Study 05</a>
</li>
<li>
  <a href="case_study_06.html">Case Study 06</a>
</li>
<li>
  <a href="case_study_07.html">Case Study 07</a>
</li>
<li>
  <a href="case_study_08.html">Case Study 08</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://avramaral.github.io/">
    <span class="fa fa-globe"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Case Study 06</h1>
<h4 class="author">André Victor Ribeiro Amaral</h4>

</div>


<div id="objectives" class="section level1 unnumbered">
<h1 class="unnumbered">Objectives</h1>
<p>In this case study, we will fit a logistic regression model. As this is the first example of this kind, we will see the basics on how to interpret the fitted model and how to visualize the results. In the next case study, we will see more on how to use logistic regression for classification problems.</p>
</div>
<div id="introduction" class="section level1" number="1">
<h1 number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>For this problem, we will analyse data collected on launch temperature and O-ring failure for the 24 Space Shuttle launches prior to the Challenger disaster of January 1986. Data were retrieved from the <a href="https://www.wiley.com/en-us/Applied+Statistics+and+Probability+for+Engineers%2C+7th+Edition-p-9781119400363"><strong>Applied Statistics and Probability for Engineers</strong> book</a>. You can download the <code>.csv</code> file <a href="./datasets/oring.csv">here</a>. The data set contains the following variables:</p>
<ol style="list-style-type: decimal">
<li><code>temperature</code> (quantitative)</li>
<li><code>oRing_fail</code> (binary): <code>1</code> means that at least one O-ring failure had occurred on that launch; and <code>0</code>, otherwise.</li>
</ol>
<div id="logistic-regression" class="section level2" number="1.1">
<h2 number="1.1"><span class="header-section-number">1.1</span> Logistic Regression</h2>
<p>Since this case study is slightly different from the previous ones, let’s start with a review of what a logistic regression model is.</p>
<p>The logistic regression model is based on the Bernoulli distribution, which has only two values, 0 and 1, and one parameter, <span class="math inline">\(\theta\)</span>, the probability of success. That is,</p>
<p><span class="math display">\[
\mathbb{P}(Y = y) = \theta^{y} (1 - \theta)^{1 - y}, ~ y = 0, 1.
\]</span></p>
<p>Also, <span class="math inline">\(\mathbb{E}(Y) = \theta\)</span> and <span class="math inline">\(\text{Var}(Y) = \theta \cdot (1 - \theta)\)</span>.</p>
<p>In this case, we assume that <span class="math inline">\(\theta(\mathbf{x})\)</span> depends on the values of <span class="math inline">\(\mathbf{x}\)</span> of the regressors through a linear combination <span class="math inline">\(\mathbf{x}^{\text{T}}\boldsymbol{\beta}\)</span> for some unknown <span class="math inline">\(\boldsymbol{\beta}\)</span>.</p>
<p>However, <span class="math inline">\(\theta(\mathbf{x})\)</span> cannot equal <span class="math inline">\(\mathbf{x}^{\text{T}}\boldsymbol{\beta}\)</span> because <span class="math inline">\(\theta\)</span> is a probability and hence takes values in <span class="math inline">\([0, 1]\)</span>, while the linear combination <span class="math inline">\(\mathbf{x}^{\text{T}}\boldsymbol{\beta}\)</span> takes values in <span class="math inline">\(\mathbb{R}\)</span>. Thus, we need a transformation to map these two expressions. In our case, we will choose the <code>logit</code> function, that is,</p>
<p><span class="math display">\[
\texttt{logit}(\theta(\mathbf{x})) = \log\left(\frac{\theta(\mathbf{x})}{1 - \theta(\mathbf{x})}\right)
\]</span></p>
<pre class="r"><code>logit &lt;- function (x) { log(x / (1 - x)) }
x &lt;- seq(0.01, 0.99, 0.01)
y &lt;- sapply(x, logit)
plot(x = x, y = y, xlab = &#39;x&#39;, ylab = &#39;logit(x)&#39;, type = &#39;l&#39;)</code></pre>
<p><img src="case_study_06_files/figure-html/unnamed-chunk-1-1.png" width="672" /></p>
<p>Thus, we can always write <span class="math inline">\(\theta(\mathbf{x})\)</span> as</p>
<p><span class="math display">\[
\theta(\mathbf{x}) = g^{-1}(\mathbf{x}^{\text{T}}\boldsymbol{\beta}) = \frac{1}{1 + \exp^{-\mathbf{x}^{\text{T}}\boldsymbol{\beta}}},
\]</span></p>
<p>such that <span class="math inline">\(g\)</span> is the <code>logit</code> transformation.</p>
</div>
</div>
<div id="exploring-the-data-set" class="section level1" number="2">
<h1 number="2"><span class="header-section-number">2</span> Exploring the data set</h1>
<p>In order to explore the data set and perform initial analyses, we have to read it (with <code>R</code>) first. Provided that the <code>.csv</code> file is saved within the <code>datasets/</code> folder, one can read the file in the following way.</p>
<pre class="r"><code>col.names &lt;- c(&#39;temperature&#39;, &#39;oRing_fail&#39;)
oring &lt;- read.csv(file = &#39;datasets/oring.csv&#39;, header = FALSE, sep = &#39;,&#39;, col.names = col.names)
head(oring, 5)</code></pre>
<pre><code>##   temperature oRing_fail
## 1          53          1
## 2          56          1
## 3          57          1
## 4          63          0
## 5          66          0</code></pre>
<p>Now, let’s see a summary of our data.</p>
<pre class="r"><code>summary(oring)</code></pre>
<pre><code>##   temperature      oRing_fail    
##  Min.   :53.00   Min.   :0.0000  
##  1st Qu.:67.00   1st Qu.:0.0000  
##  Median :70.00   Median :0.0000  
##  Mean   :69.92   Mean   :0.2917  
##  3rd Qu.:75.25   3rd Qu.:1.0000  
##  Max.   :81.00   Max.   :1.0000</code></pre>
<p>However, as <code>oRing_fail</code> is being interpreted as numeric, we have to convert it to factor (categorical variable) before conducting any analysis.</p>
<pre class="r"><code>oring$oRing_fail &lt;- as.factor(oring$oRing_fail)
summary(oring)</code></pre>
<pre><code>##   temperature    oRing_fail
##  Min.   :53.00   0:17      
##  1st Qu.:67.00   1: 7      
##  Median :70.00             
##  Mean   :69.92             
##  3rd Qu.:75.25             
##  Max.   :81.00</code></pre>
<p>Now, we can graph the data using the <code>plot</code> command for the <code>oring</code> data set.</p>
<pre class="r"><code>plot(x = oring$temperature, y = as.numeric(as.character(oring$oRing_fail)))</code></pre>
<p><img src="case_study_06_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The above plot is not very interesting since we do not have much data, but we can observe, for instance, that failures have occurred at lower temperature (<span class="math inline">\(&lt; 60\)</span>) with few exceptions. But now, we can fit our model.</p>
</div>
<div id="fitting-a-model" class="section level1" number="3">
<h1 number="3"><span class="header-section-number">3</span> Fitting a model</h1>
<p>Although we did not say this before, the logistic regression (as the linear regression) are just special cases of a class of models named Generalized Linear Models (GLM), and to fit such a model, we will use the <code>glm()</code> function from base <code>R</code>. We can see the function help by entering the <code>?glm</code> command.</p>
<pre class="r"><code>model &lt;- glm(formula = oRing_fail ~ temperature, data = oring, family = binomial(link = &#39;logit&#39;)) # with logit link function
summary(model)</code></pre>
<pre><code>## 
## Call:
## glm(formula = oRing_fail ~ temperature, family = binomial(link = &quot;logit&quot;), 
##     data = oring)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.2125  -0.8253  -0.4706   0.5907   2.0512  
## 
## Coefficients:
##             Estimate Std. Error z value Pr(&gt;|z|)  
## (Intercept) 10.87535    5.70291   1.907   0.0565 .
## temperature -0.17132    0.08344  -2.053   0.0400 *
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 28.975  on 23  degrees of freedom
## Residual deviance: 23.030  on 22  degrees of freedom
## AIC: 27.03
## 
## Number of Fisher Scoring iterations: 4</code></pre>
<p>The above summary must be interpreted in a similar as before. However, recall that the estimates and their standard errors are in <code>logits</code>. That is,</p>
<p><span class="math display">\[\begin{align*}
\theta(\mathbf{x}) = \frac{1}{1 + \exp^{-(10.875 -0.171\texttt{temperature})}}.
\end{align*}\]</span></p>
<p>Also, we can plot our fitted model.</p>
<pre class="r"><code>xx &lt;- seq(50, 85, 0.1)
yy &lt;- predict(model, data.frame(temperature = xx), type = &#39;response&#39;) 
# logistic_transf &lt;- function (x) { 1 / (1 + exp(-x)) }
# yy &lt;- sapply(X = yy, FUN = logistic_transf)
plot(x = oring$temperature, y = as.numeric(as.character(oring$oRing_fail)), pch = 19, col = &#39;red&#39;)
lines(xx, yy, col = &#39;blue&#39;)</code></pre>
<p><img src="case_study_06_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p><strong>Remark:</strong> The following part is optional.</p>
<p>However, it might difficult to know how good the fit of the model is when data are shown only as 0s and 1s. In this case, we will divide the ranges of temperatures into three, count how many success (in this case, a success is having a failure for the O-ring) and failures, calculate the main proportion incidence in each third, <span class="math inline">\(\theta\)</span>, and add these estimates as points along with their standard error bars <span class="math inline">\(\sqrt{\theta(1 - \theta)/n}\)</span>. Regarding the standard error bars, recall that, if <span class="math inline">\(Y_i \sim Bernoulli(\theta)\)</span>, <span class="math inline">\(\forall i\)</span>, then <span class="math inline">\(\text{Var}(\bar{\theta}) = \text{Var}(\sum Y_i / n) = \theta(1 - \theta)/n\)</span>.</p>
<p>To do this, we obtain the break points for the <code>temperature</code>, and count the number of 1s in each interval.</p>
<pre class="r"><code>(tp &lt;- cut(oring$temperature, 3))</code></pre>
<pre><code>##  [1] (53,62.3]   (53,62.3]   (53,62.3]   (62.3,71.7] (62.3,71.7] (62.3,71.7]
##  [7] (62.3,71.7] (62.3,71.7] (62.3,71.7] (62.3,71.7] (62.3,71.7] (62.3,71.7]
## [13] (62.3,71.7] (62.3,71.7] (71.7,81]   (71.7,81]   (71.7,81]   (71.7,81]  
## [19] (71.7,81]   (71.7,81]   (71.7,81]   (71.7,81]   (71.7,81]   (71.7,81]  
## Levels: (53,62.3] (62.3,71.7] (71.7,81]</code></pre>
<pre class="r"><code>tapply(as.numeric(as.character(oring$oRing_fail)), tp, sum)</code></pre>
<pre><code>##   (53,62.3] (62.3,71.7]   (71.7,81] 
##           3           3           1</code></pre>
<p>Next, based on the total number of cases in each interval (<code>table(tp)</code>), we can compute the probability of success by dividing the number of success by the number of cases.</p>
<pre class="r"><code>table(tp)</code></pre>
<pre><code>## tp
##   (53,62.3] (62.3,71.7]   (71.7,81] 
##           3          11          10</code></pre>
<pre class="r"><code>tapply(as.numeric(as.character(oring$oRing_fail)), tp, sum) / table(tp)</code></pre>
<pre><code>##   (53,62.3] (62.3,71.7]   (71.7,81] 
##   1.0000000   0.2727273   0.1000000</code></pre>
<p>Then, we can do the plot. The following piece of code puts everything together.</p>
<pre class="r"><code>xx &lt;- seq(50, 85, 0.1)
yy &lt;- predict(model, data.frame(temperature = xx), type = &#39;response&#39;) 
plot(x = oring$temperature, y = as.numeric(as.character(oring$oRing_fail)), xlab = &#39;temperature&#39;, ylab = &#39;oRing_fail&#39;, pch = 19, col = &#39;red&#39;)
lines(xx, yy, col = &#39;blue&#39;)

delta_temp &lt;- (max(oring$temperature) - min(oring$temperature)) / 3
left &lt;- min(oring$temperature) + delta_temp / 2
mid &lt;- left + delta_temp
right &lt;- mid + delta_temp
lmr &lt;- c(left, mid, right)
tp &lt;- cut(oring$temperature, 3)
mean_prop &lt;- as.vector(tapply(as.numeric(as.character(oring$oRing_fail)), tp, sum) / table(tp))
se &lt;- sqrt(mean_prop * (1 - mean_prop) / table(tp))

points(lmr, mean_prop, pch = 16, col = &#39;magenta&#39;)
for (i in 1:3) lines(c(lmr[i], lmr[i]), c(mean_prop[i] + se[i], mean_prop[i] - se[i]), col = &#39;magenta&#39;)</code></pre>
<p><img src="case_study_06_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>From the above plot, we can see that, our fitted model (excepted, maybe, for low temperatures) describes well the data.</p>
</div>
<div id="predicting-unknown-values" class="section level1" number="4">
<h1 number="4"><span class="header-section-number">4</span> Predicting unknown values</h1>
<p>The actual temperature at the Challenger launch was 31∘F. Although our model may not give us good predictions for such temperature (it is way out of our observed range of values), we can compute the probability of observing at least one O-ring failure during the launch in the following way</p>
<pre class="r"><code>newdata &lt;- data.frame(temperature = 35)
predict(model, newdata = newdata, type = &#39;response&#39;)</code></pre>
<pre><code>##         1 
## 0.9924538</code></pre>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
