<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="André Victor Ribeiro Amaral" />


<title>Case Study 04</title>

<script src="site_libs/header-attrs-2.11/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>





<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Exercises in Linear Models</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="case_study_01.html">Case Study 01</a>
</li>
<li>
  <a href="case_study_02.html">Case Study 02</a>
</li>
<li>
  <a href="case_study_03.html">Case Study 03</a>
</li>
<li>
  <a href="case_study_04.html">Case Study 04</a>
</li>
<li>
  <a href="case_study_05.html">Case Study 05</a>
</li>
<li>
  <a href="case_study_06.html">Case Study 06</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://avramaral.github.io/">
    <span class="fa fa-globe"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Case Study 04</h1>
<h4 class="author">André Victor Ribeiro Amaral</h4>

</div>


<div id="objectives" class="section level1 unnumbered">
<h1 class="unnumbered">Objectives</h1>
<p>In this case study, we will fit a multiple linear regression model. This example will be simple, and we will also be able to visualize the estimated surface (most of the time, it is not possible neither important). To do this, we will fit the model, check the assumptions, interpret it, visualize the estimated surface, and predict (and plot) new values based on this fitted model.</p>
</div>
<div id="introduction" class="section level1" number="1">
<h1><span class="header-section-number">1</span> Introduction</h1>
<p>For this problem, we will analyse data collected in an observational study in a semiconductor manufacturing plant. Data were retrieved from the <a href="https://www.wiley.com/en-us/Applied+Statistics+and+Probability+for+Engineers%2C+7th+Edition-p-9781119400363"><strong>Applied Statistics and Probability for Engineers</strong> book</a>. You can download the <code>.csv</code> file <a href="./datasets/wire_bond.csv">here</a>. In this plant, the finished semiconductor is wire-bonded to a frame. The variables reported are pull strength (a measure of the amount of force required to break the bond), the wire length, and the height of the die. Thus, the data set contains following the variables:</p>
<ol style="list-style-type: decimal">
<li><code>pull_strength</code> (quantitative)</li>
<li><code>wire_length</code> (quantitative)</li>
<li><code>height</code> (quantitative)</li>
</ol>
</div>
<div id="exploring-the-data-set" class="section level1" number="2">
<h1><span class="header-section-number">2</span> Exploring the data set</h1>
<p>In order to explore the data set and perform initial analyses, we have to read it (with <code>R</code>) first. Provided that the <code>.csv</code> file is saved within the <code>datasets/</code> folder, one can read the file in the following way.</p>
<pre class="r"><code>col.names &lt;- c(&#39;pull_strength&#39;, &#39;wire_length&#39;, &#39;height&#39;)
data &lt;- read.csv(file = &#39;datasets/wire_bond.csv&#39;, header = FALSE, sep = &#39;,&#39;, col.names = col.names)
head(data, 5)</code></pre>
<pre><code>##   pull_strength wire_length height
## 1          9.95           2     50
## 2         24.45           8    110
## 3         31.75          11    120
## 4         35.00          10    550
## 5         25.02           8    295</code></pre>
<p>Now, let’s see a summary of our data.</p>
<pre class="r"><code>summary(data)</code></pre>
<pre><code>##  pull_strength    wire_length        height     
##  Min.   : 9.60   Min.   : 1.00   Min.   : 50.0  
##  1st Qu.:17.08   1st Qu.: 4.00   1st Qu.:200.0  
##  Median :24.45   Median : 8.00   Median :360.0  
##  Mean   :29.03   Mean   : 8.24   Mean   :331.8  
##  3rd Qu.:37.00   3rd Qu.:11.00   3rd Qu.:500.0  
##  Max.   :69.00   Max.   :20.00   Max.   :600.0</code></pre>
<p>In this case, there are no missing values—which is great. However, since we want to use most information from this data set, it might not be easy to visualize how one attribute (in our case <code>pull_strength</code>) can be written as a function of more than two variables at the same time. Fortunately, we can still plot data in 3D (using the <code>scatterplot3d()</code> function from the <code>scatterplot3d</code> package).</p>
<pre class="r"><code>library(&#39;scatterplot3d&#39;)
scatterplot3d(data$wire_length, data$height, data$pull_strength, color = 2, pch = 19, angle = 70)</code></pre>
<p><img src="case_study_04_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
<p>Also, it is useful to see how variables are correlated. To do this, we can plot (at least) two types of graphs; in this case, we will use the <code>scatterplotMatrix()</code> function from the <code>car</code> package, and the <code>corrplot.mixed()</code> function from the <code>corrplot</code> package to plot the correlation (from <code>cor()</code>) matrix.</p>
<pre class="r"><code>library(&#39;car&#39;)

scatterplotMatrix(data)</code></pre>
<p><img src="case_study_04_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre class="r"><code>library(&#39;corrplot&#39;)</code></pre>
<pre><code>## corrplot 0.92 loaded</code></pre>
<pre class="r"><code>corrplot.mixed(cor(data))</code></pre>
<p><img src="case_study_04_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>From the second plot, we can see that <code>pull_strength</code> is highly correlated with <code>wire_length</code>, and this relation is detailed in the first plot. These graphs will be even more useful once we have more variables (as we will see in our next problem).</p>
</div>
<div id="fitting-a-model" class="section level1" number="3">
<h1><span class="header-section-number">3</span> Fitting a model</h1>
<p>Our very first task will be fitting a model with all variables so that we can try to explain how <code>pull_strength</code> relates with the other variables. We can do this in the following way.</p>
<pre class="r"><code>model &lt;- lm(formula = pull_strength ~ ., data = data)
summary(model)</code></pre>
<pre><code>## 
## Call:
## lm(formula = pull_strength ~ ., data = data)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -3.865 -1.542 -0.362  1.196  5.841 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 2.263791   1.060066   2.136 0.044099 *  
## wire_length 2.744270   0.093524  29.343  &lt; 2e-16 ***
## height      0.012528   0.002798   4.477 0.000188 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 2.288 on 22 degrees of freedom
## Multiple R-squared:  0.9811, Adjusted R-squared:  0.9794 
## F-statistic: 572.2 on 2 and 22 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>As we can see from the summary, for a significance level of <span class="math inline">\(5\%\)</span>, all coefficients are different than zero. Thus, we should keep them (for our next problem, we will try to simplify the model further).</p>
<p>Once we have the model, a next step would be performing a residual analysis. To do this, we can plot the diagnostic graphs and run the appropriate tests.</p>
<pre class="r"><code>plot(model, which = c(1, 2))</code></pre>
<p><img src="case_study_04_files/figure-html/unnamed-chunk-7-1.png" width="672" /><img src="case_study_04_files/figure-html/unnamed-chunk-7-2.png" width="672" /></p>
<p>The plot seems okay, but we still have to do the tests. As a remark, and as extracted from <a href="https://stats.stackexchange.com/questions/239157/what-does-the-residuals-vs-fitted-regression-line-express">this page</a>, “<em>the red line is a LOWESS fit to your residuals vs fitted plot. Basically, it’s smoothing over the points to look for certain kinds of patterns in the residuals. For example, if you fit a linear regression on data that looked like <span class="math inline">\(y = x^2\)</span>, you’d see a noticeable bowed shape</em>”. Regarding the tests, we have the following</p>
<pre class="r"><code>ncvTest(model)</code></pre>
<pre><code>## Non-constant Variance Score Test 
## Variance formula: ~ fitted.values 
## Chisquare = 0.04524206, Df = 1, p = 0.83156</code></pre>
<pre class="r"><code>shapiro.test(resid(model))</code></pre>
<pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  resid(model)
## W = 0.95827, p-value = 0.381</code></pre>
<p>Also, from the test results, we fail to reject the equal variance and normality assumptions, meaning that we have a good model for our data.</p>
<p>In particular, the model is given by</p>
<p><span class="math display">\[\begin{align*}
\texttt{pull_strength}_i &amp;= 2.264 + 2.744\texttt{wire_length}_i + 0.013\texttt{height}_i
\end{align*}\]</span></p>
<p>And we can plot the fitted model in the following way</p>
<pre class="r"><code>plot3d &lt;- scatterplot3d(data$wire_length, data$height, data$pull_strength, color = 2, pch = 19, angle = 70)
plot3d$plane3d(model)</code></pre>
<p><img src="case_study_04_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="predicting-unknown-values" class="section level1" number="4">
<h1><span class="header-section-number">4</span> Predicting unknown values</h1>
<p>Now that we have a “good” fitted model, we can predict, the value of <code>pull_strength</code> for new values of <code>wire_length</code> and <code>height</code>. For instance, we can predict the value of <code>pull_strength</code>, such that <code>wire_length</code> is equal to 7.5 and 12.5 and <code>height</code> is equal to 150 and 450, respectively. <strong>Notice that your new points must lie within the range for the observed data</strong>, otherwise your model may not be appropriate for predicting extrapolated points.</p>
<pre class="r"><code>newdata &lt;- data.frame(wire_length = c(7.5, 12.5), height = c(150, 450))

(pred1 &lt;- predict(object = model, newdata = newdata, interval = &#39;confidence&#39;))</code></pre>
<pre><code>##        fit      lwr      upr
## 1 24.72499 23.33957 26.11040
## 2 42.20468 40.92987 43.47948</code></pre>
<pre class="r"><code>(pred2 &lt;- predict(object = model, newdata = newdata, interval = &#39;prediction&#39;))</code></pre>
<pre><code>##        fit      lwr      upr
## 1 24.72499 19.78175 29.66822
## 2 42.20468 37.29130 47.11805</code></pre>
<pre class="r"><code>newdata &lt;- cbind(newdata, pull_strength = pred1[, 1])
data &lt;- rbind(data, newdata)

plot3d &lt;- scatterplot3d(data$wire_length, data$height, data$pull_strength, color = c(rep(2, nrow(data) - 2), 3, 3), pch = 19, angle = 70)
plot3d$plane3d(model)
legend(&#39;topleft&#39;, c(&#39;Observed data&#39;, &#39;New data&#39;), col = c(2, 3), pch = 19)</code></pre>
<p><img src="case_study_04_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>From the above predicted values, notice that this time, we added the confidence interval and the prediction interval. As explained <a href="https://www.wiley.com/en-us/Applied+Statistics+and+Probability+for+Engineers%2C+7th+Edition-p-9781119400363">Applied Statistics and Probability for Engineers book</a>, “<em>the prediction interval is always wider than the confidence interval. The confidence interval expresses the error in estimating the mean of a distribution, and the prediction interval expresses the error in predicting a future observation from the distribution at the point <span class="math inline">\(\mathbf{x}_0\)</span>. This must include the error in estimating the mean at that point as well as the inherent variability in the random variable <code>wire_length</code> at the same value <span class="math inline">\(\mathbf{x} = \mathbf{x}_0\)</span></em>”.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
